### ISSUE TITLE
JUnit tests in org.eclipse.jface.text.tests.contentassist are failing on Windows and Mac

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#35]
This is a duplicate of [Bug 571316](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571316) - JUnit tests in org.eclipse.jface.text.tests.contentassist are failing on Windows and Mac

I will close the bug in bugzilla and this bug will be tracked here.

The JFace text tests in org.eclipse.jface.text.tests.contentassist fail in the nightly build as below

Windows
1) testCompleteActivationChar

Both Windows and Mac
1) testSyncFailureNPE

**Comment by ktatavarthi** [comment]
#9 is a duplicate of this bug.

**Comment by ktatavarthi** [comment]
The below test failed in the IBuild [I20220601-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testResults.php)  on Windows and Mac

[Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html)
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar 
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE


Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220817-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220831-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On [MacM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below test failed in the IBuild [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar

**Comment by ktatavarthi** [comment]
The below tests faile in the build [I20221117-1330](https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) on Windows
  - org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
  - org.eclipse.jface.text.tests.contentassist.ContextInformationPresenterTest.testContextInfo_withStyledTextPresentation
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_keyEsc
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_validRange

**Comment by ktatavarthi** [comment]
The below tests fail in the build [I20221123-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) on Windows

    org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
    org.eclipse.jface.text.tests.contentassist.ContextInformationPresenterTest.testContextInfo_withStyledTextPresentation
    org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_keyEsc
    org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_validRange

**Comment by jukzi** [comment]
ContextInformationTest's randomly fails locally on WIndows every ~2nd time. for MAC and Linux ContextInformationTest.testContextInfo_hide_focusOut() is already disabled.

**Comment by jukzi** [comment]
Still an error:
https://download.eclipse.org/eclipse/downloads/drops4/I20230531-1800/testresults/html/org.eclipse.jface.text.tests_ep428I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Not unique new shell found expected:<1> but was:<0>
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:235)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar(AsyncContentAssistTest.java:182)

```

**Comment by jukzi** [comment]
still randomly failing on win
https://download.eclipse.org/eclipse/downloads/drops4/I20230620-1800/testresults/html/org.eclipse.jface.text.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Not unique new shell found expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:235)

```
