### ISSUE TITLE
JUnit tests in org.eclipse.search.tests.filesearch.PositionTrackerTest are failing on Mac

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#54]
In the Build [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html), the below tests in in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testResults.php), the below test in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on [macM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) and [macX86_64](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
 - testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220831-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed 


on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.search.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.search.tests_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by Shee43** [comment]
In the Build [I20230405-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed 

on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Shee43** [comment]
In the Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
> 
> ```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```
>
>
In the Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
>
on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
>
>```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by Shee43** [comment]
> In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
> > 
> 
> on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
>```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```
>
> In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
> > 
> 
> on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.search.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
> 
>  ```
> java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 >```

**Comment by Shee43** [comment]
In the Build [I20230601-1220](https://download.eclipse.org/eclipse/downloads/drops4/I20230601-1220/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230601-1220/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)

> ```
> java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

**Comment by Shee43** [comment]
In the Build [I20230605-0440](https://download.eclipse.org/eclipse/downloads/drops4/I20230605-0440/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230605-0440/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
> 
 > ```
> java.lang.AssertionError
> at org.junit.Assert.fail(Assert.java:87)
> at org.junit.Assert.assertTrue(Assert.java:42)
> at org.junit.Assert.assertNotNull(Assert.java:713)
> at org.junit.Assert.assertNotNull(Assert.java:723)
> at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
> at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```
