### ISSUE TITLE
"Unhandled event loop exception" on "Cancel user task"

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.text#65]
- Tried to edit a file during the long running build.
- Blocking progress dialog shows me, that I have to wait.
- I don't wait so click on "Cancel user operation"
- "Unhandled event loop exception" error logged to the error log

This is coming from https://bugs.eclipse.org/bugs/show_bug.cgi?id=577511 / https://github.com/eclipse-platform/eclipse.platform.text/commit/0f409d6f3d6b590242268c9d97c3a0107737dfa7 / https://github.com/eclipse-platform/eclipse.platform.text/pull/4.

If we re-throw this exception in order to fix something, we should not log it as "Unhandled event loop exception" **error**. A warning, if any, makes sense.

I assume org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(Throwable) should ignore or log OperationCanceledException instances, but might be there is a better idea.

```
eclipse.buildId=4.25.0.202207280832
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data file:/tmp/wsp_rnd_smoke/ -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Thu Jul 28 11:41:09 CEST 2022
Unhandled event loop exception

org.eclipse.core.runtime.OperationCanceledException
	at org.eclipse.ui.texteditor.AbstractTextEditor.validateState(AbstractTextEditor.java:4906)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$4(AbstractTextEditor.java:4947)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.texteditor.AbstractTextEditor.validateEditorInputState(AbstractTextEditor.java:4947)
	at org.eclipse.ui.texteditor.StatusTextEditor.validateEditorInputState(StatusTextEditor.java:159)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.validateEditorInputState(AbstractDecoratedTextEditor.java:1055)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener$Validator.verifyText(AbstractTextEditor.java:392)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:277)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1316)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7607)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8539)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2540)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6222)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6253)
```

**Comment by iloveeclipse** [comment]
Note: since the original change seem to have no effect, the easiest solution is to revert it.

**Comment by jukzi** [comment]
I also get an Exception logged. However the patch still works - i do need to cancel only once - with a totally other stacktrace:
```
org.eclipse.core.runtime.OperationCanceledException
	at org.eclipse.ui.texteditor.AbstractTextEditor.validateState(AbstractTextEditor.java:4906)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$4(AbstractTextEditor.java:4947)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.texteditor.AbstractTextEditor.validateEditorInputState(AbstractTextEditor.java:4947)
	at org.eclipse.ui.texteditor.StatusTextEditor.validateEditorInputState(StatusTextEditor.java:159)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.validateEditorInputState(AbstractDecoratedTextEditor.java:1055)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener$Validator.verifyText(AbstractTextEditor.java:392)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:277)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7607)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8539)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2540)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6222)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6253)
	at org.eclipse.swt.custom.StyledText.lambda$28(StyledText.java:5932)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1542)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4868)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4746)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

I did edit a **.java** File. I guess you saved a .txt file? But still even with a text file the patch still works for me!
Better then revert:  catch the exception to not log it.

**Comment by iloveeclipse** [comment]
> with a totally other stacktrace

What do you mean by "totally other"? I cut the stack at the event loop. The rest above is same, and event loop is different anyway on different platforms.

> I did edit a **.java** File. I guess you saved a .txt file

I did exact what was described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=577511.
Open Java file. Run build. Type garbage in file. Click few times on cancel to get rid of the dialog. Exception.

> Better then revert: catch the exception to not log it.

The "fix" is probably only Windows specific, and relies on how event loop handling is done. before the change, the exception was catched at the editor level and that worked on all platforms.

Note: https://github.com/eclipse-platform/eclipse.platform.text/pull/73 does have **no effect** on Linux for the original issue, because it essentially restores original behavior. I wonder how that is supposed to fix the problem on Windows?
