### ISSUE TITLE
AsyncContentAssistTest : testSyncFailureNPE fails in I-build both on Windows and Mac

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#75]
org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE failed in the build [I20220519-0130](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/) with the below error

```
Widget is disposed

org.eclipse.swt.SWTException: Widget is disposed
at org.eclipse.swt.SWT.error(SWT.java:4918)
at org.eclipse.swt.SWT.error(SWT.java:4833)
at org.eclipse.swt.SWT.error(SWT.java:4804)
at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1443)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest$2.run(AsyncContentAssistTest.java:159)
at org.eclipse.swt.widgets.Display.runTimers(Display.java:4578)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3957)
at org.eclipse.jface.text.tests.util.DisplayHelper.driveEventQueue(DisplayHelper.java:126)
at org.eclipse.jface.text.tests.util.DisplayHelper.waitForCondition(DisplayHelper.java:78)
at org.eclipse.jface.text.tests.util.DisplayHelper.sleep(DisplayHelper.java:105)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE(AsyncContentAssistTest.java:100)
```

Link to test results

- [I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-macM1-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- [I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-mac64-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- [I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-win32-java11](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by ktatavarthi** [comment]
org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE failed in the build [I20220817-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800)  on both Windows and Mac

Link to test results

- [I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- [I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- [I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by ktatavarthi** [comment]
org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE failed in the build [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800)  on both Windows and Mac

Link to test results

- [I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- [I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- [I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by ktatavarthi** [comment]
org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE failed in the build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800)  on both Windows and Mac

Link to test results

- [I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-macM1-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- [I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-mac64-java17](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- [I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by jukzi** [comment]
even though testCompleteActivationChar failed it was an event from testCompleteActivationChar (AsyncContentAssistTest.java:159) that failed

```
 org.eclipse.swt.SWTException: Widget is disposed
at org.eclipse.swt.SWT.error(SWT.java:4918)
at org.eclipse.swt.SWT.error(SWT.java:4833)
at org.eclipse.swt.SWT.error(SWT.java:4804)
at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1069)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest$2.run(AsyncContentAssistTest.java:159) <-----
at org.eclipse.swt.widgets.Display.runTimer(Display.java:4154)
at org.eclipse.swt.widgets.Display.messageProc(Display.java:3263)
at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3631)
at org.eclipse.jface.text.tests.util.DisplayHelper.driveEventQueue(DisplayHelper.java:126)
at org.eclipse.jface.text.tests.util.DisplayHelper.waitForCondition(DisplayHelper.java:78)
at org.eclipse.jface.text.tests.util.DisplayHelper.sleep(DisplayHelper.java:105)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE(AsyncContentAssistTest.java:100) <-----
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:226)
at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:202)
at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:52)
at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35)
at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:43)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
at org.eclipse.core.launcher.Main.main(Main.java:44)
```

**Comment by jukzi** [comment]
caused by
https://github.com/eclipse-platform/eclipse.platform.text/issues/35
