### ISSUE TITLE
StringIndexOutOfBoundsException during File Search

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.text#79]
![image](https://user-images.githubusercontent.com/51790620/186518481-0c2ddf37-dbc6-4551-818c-554f1aa646b7.png)

```
!MESSAGE An internal error occurred during: "Searching for pattern 'Hello'...".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 11
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at java.base/java.lang.Character.codePointAt(Character.java:8264)
	at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4296)
	at java.base/java.util.regex.Matcher.match(Matcher.java:1756)
	at java.base/java.util.regex.Matcher.matches(Matcher.java:713)
	at org.eclipse.search.ui.text.FileTextSearchScope.matchesFileName(FileTextSearchScope.java:226)
	at org.eclipse.search.ui.text.FileTextSearchScope.contains(FileTextSearchScope.java:220)
	at org.eclipse.search.internal.core.text.FilesOfScopeCalculator.visit(FilesOfScopeCalculator.java:41)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:127)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at org.eclipse.search.internal.core.text.FilesOfScopeCalculator.process(FilesOfScopeCalculator.java:56)
	at org.eclipse.search.core.text.TextSearchScope.evaluateFilesInScope(TextSearchScope.java:86)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:430)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:60)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:232)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jukzi** [comment]
The single java.util.regex.Matcher used in org.eclipse.search.ui.text.FileTextSearchScope.fPositiveFileNameMatcher is shared across threads but documented to "Instances of this class are not safe for use by multiple concurrentthreads. "

**Comment by jukzi** [comment]
also dump that one can initiate a second search while the first is still running:
![image](https://user-images.githubusercontent.com/51790620/186520298-c67ee97f-05fc-4b9b-ab29-9dacc540b183.png)
the old search should be canceled before starting another search.

**Comment by vogella** [comment]
@jukzi did https://github.com/eclipse-platform/eclipse.platform.text/commit/f2f673ba38d50fb224bf984f429f585eea74d605 fix this issue?
