### ISSUE TITLE
Search test PositionTrackerTest.testInsertInsideMatch fails on Mac in the I-build

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.text#80]
The test org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch failed in the build [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testResults.php) on [Mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html) and [MacM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) with the below error

```
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82ts/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and [MacM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) with the below error
```

**Comment by ktatavarthi** [comment]
This bug is a duplicate of https://github.com/eclipse-platform/eclipse.platform.text/issues/54. So closing this bug
