### ISSUE TITLE
NPE in AbstractLineTracker.set(AbstractLineTracker.java:183)

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.text#91]
Found this (random) issue in our test logs.
I don't have reproducer.

`org.eclipse.core.internal.filebuffers.ResourceFileBuffer.FileSynchronizer` works directly on resource notification thread and tries to update some jface document (opened editor?). That goes wrong because the document seem to be already flushed or closed.

If I see it right, `org.eclipse.core.internal.filebuffers.ResourceFileBuffer.FileSynchronizer` should update documents on UI thread.
```
!ENTRY org.eclipse.core.filebuffers 4 0 2022-09-20 06:02:19.279
!MESSAGE Exception when synchronizing
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jface.text.AbstractLineTracker.set(AbstractLineTracker.java:183)
	at org.eclipse.jface.text.AbstractDocument.set(AbstractDocument.java:1134)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.set(SynchronizableDocument.java:196)
	at org.eclipse.core.internal.filebuffers.ResourceTextFileBuffer.handleFileContentChanged(ResourceTextFileBuffer.java:458)
	at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$FileSynchronizer$2.execute(ResourceFileBuffer.java:151)
	at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$SafeFileChange.run(ResourceFileBuffer.java:86)
	at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$FileSynchronizer.resourceChanged(ResourceFileBuffer.java:186)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:381)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1503)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2327)
	at org.eclipse.core.internal.events.NotificationManager$NotifyJob.run(NotificationManager.java:44)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by iloveeclipse** [comment]
OK, I see `org.eclipse.jface.text.AbstractLineTracker.stopRewriteSession(DocumentRewriteSession, String)` nulls out two non-volatile fields one after each other without locking, and at same time `org.eclipse.jface.text.AbstractLineTracker.hasActiveRewriteSession()` may query the value in parallel and say "all right" so that call to `org.eclipse.jface.text.AbstractLineTracker.set(String)` runs into NPE because it finally hits the null written by `AbstractLineTracker.stopRewriteSession()`.
